# Generated by Django 5.2.17 on 2026-09-30 20:52

import cms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Appointment phone',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Existing website copy key. Keep this key unchanged when editing text.', max_length=150, unique=True)),
                ('en', models.TextField(verbose_name='English')),
                ('hi', models.TextField(blank=True, verbose_name='Hindi')),
                ('mr', models.TextField(blank=True, verbose_name='Marathi')),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page text',
                'verbose_name_plural': 'Page text',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name (English)')),
                ('name_hi', models.CharField(blank=True, max_length=250, verbose_name='Name (Hindi)')),
                ('name_mr', models.CharField(blank=True, max_length=250, verbose_name='Name (Marathi)')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('specialty', models.CharField(choices=[('child', 'Child specialist'), ('dental', 'Dentist')], max_length=10)),
                ('qualifications', models.CharField(max_length=500)),
                ('experience_en', models.TextField(blank=True, verbose_name='Experience (English)')),
                ('experience_hi', models.TextField(blank=True, verbose_name='Experience (Hindi)')),
                ('experience_mr', models.TextField(blank=True, verbose_name='Experience (Marathi)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Biography (English)')),
                ('bio_hi', models.TextField(blank=True, verbose_name='Biography (Hindi)')),
                ('bio_mr', models.TextField(blank=True, verbose_name='Biography (Marathi)')),
                ('consultation_en', models.TextField(blank=True, verbose_name='Consultation (English)')),
                ('consultation_hi', models.TextField(blank=True, verbose_name='Consultation (Hindi)')),
                ('consultation_mr', models.TextField(blank=True, verbose_name='Consultation (Marathi)')),
                ('registration', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='doctors/', validators=[cms.validators.image_upload])),
                ('photo_url', models.CharField(blank=True, max_length=1000, validators=[cms.validators.safe_asset_url])),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name (English)')),
                ('name_hi', models.CharField(blank=True, max_length=250, verbose_name='Name (Hindi)')),
                ('name_mr', models.CharField(blank=True, max_length=250, verbose_name='Name (Marathi)')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('description_mr', models.TextField(blank=True, verbose_name='Description (Marathi)')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_en', models.CharField(max_length=500, verbose_name='Question (English)')),
                ('question_hi', models.CharField(blank=True, max_length=500, verbose_name='Question (Hindi)')),
                ('question_mr', models.CharField(blank=True, max_length=500, verbose_name='Question (Marathi)')),
                ('answer_en', models.TextField(verbose_name='Answer (English)')),
                ('answer_hi', models.TextField(blank=True, verbose_name='Answer (Hindi)')),
                ('answer_mr', models.TextField(blank=True, verbose_name='Answer (Marathi)')),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label_en', models.CharField(max_length=150, verbose_name='Label (English)')),
                ('label_hi', models.CharField(blank=True, max_length=150, verbose_name='Label (Hindi)')),
                ('label_mr', models.CharField(blank=True, max_length=150, verbose_name='Label (Marathi)')),
                ('times_en', models.CharField(max_length=250, verbose_name='Times (English)')),
                ('times_hi', models.CharField(blank=True, max_length=250, verbose_name='Times (Hindi)')),
                ('times_mr', models.CharField(blank=True, max_length=250, verbose_name='Times (Marathi)')),
                ('note_en', models.CharField(blank=True, max_length=500, verbose_name='Note (English)')),
                ('note_hi', models.CharField(blank=True, max_length=500, verbose_name='Note (Hindi)')),
                ('note_mr', models.CharField(blank=True, max_length=500, verbose_name='Note (Marathi)')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name (English)')),
                ('name_hi', models.CharField(blank=True, max_length=250, verbose_name='Name (Hindi)')),
                ('name_mr', models.CharField(blank=True, max_length=250, verbose_name='Name (Marathi)')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('description_mr', models.TextField(blank=True, verbose_name='Description (Marathi)')),
                ('department', models.CharField(choices=[('child', 'Child care'), ('dental', 'Dental care')], max_length=10)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name (English)')),
                ('name_hi', models.CharField(blank=True, max_length=250, verbose_name='Name (Hindi)')),
                ('name_mr', models.CharField(blank=True, max_length=250, verbose_name='Name (Marathi)')),
                ('address_en', models.TextField(verbose_name='Address (English)')),
                ('address_hi', models.TextField(blank=True, verbose_name='Address (Hindi)')),
                ('address_mr', models.TextField(blank=True, verbose_name='Address (Marathi)')),
                ('about_en', models.TextField(verbose_name='Introduction (English)')),
                ('about_hi', models.TextField(blank=True, verbose_name='Introduction (Hindi)')),
                ('about_mr', models.TextField(blank=True, verbose_name='Introduction (Marathi)')),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('maps_url', models.CharField(blank=True, max_length=1000, validators=[cms.validators.safe_external_url])),
                ('emergency_24h', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='hospital/', validators=[cms.validators.image_upload])),
                ('logo_url', models.CharField(blank=True, help_text='Fallback image; use HTTPS or /static/ or /media/.', max_length=1000, validators=[cms.validators.safe_asset_url])),
                ('hero_image', models.ImageField(blank=True, upload_to='hospital/', validators=[cms.validators.image_upload])),
                ('hero_image_url', models.CharField(blank=True, max_length=1000, validators=[cms.validators.safe_asset_url])),
                ('certification_title_en', models.CharField(blank=True, max_length=250, verbose_name='Certification title (English)')),
                ('certification_title_hi', models.CharField(blank=True, max_length=250, verbose_name='Certification title (Hindi)')),
                ('certification_title_mr', models.CharField(blank=True, max_length=250, verbose_name='Certification title (Marathi)')),
                ('certification_body_en', models.TextField(blank=True, verbose_name='Certification details (English)')),
                ('certification_body_hi', models.TextField(blank=True, verbose_name='Certification details (Hindi)')),
                ('certification_body_mr', models.TextField(blank=True, verbose_name='Certification details (Marathi)')),
                ('certification_number', models.CharField(blank=True, max_length=100)),
                ('certification_valid_from', models.DateField(blank=True, null=True)),
                ('certification_valid_to', models.DateField(blank=True, null=True)),
                ('certification_image', models.ImageField(blank=True, upload_to='certification/', validators=[cms.validators.image_upload])),
                ('certification_image_url', models.CharField(blank=True, max_length=1000, validators=[cms.validators.safe_asset_url])),
                ('certificate', models.FileField(blank=True, upload_to='certification/', validators=[cms.validators.pdf_upload])),
                ('certificate_url', models.CharField(blank=True, max_length=1000, validators=[cms.validators.safe_asset_url])),
            ],
            options={
                'verbose_name': 'Hospital settings',
                'verbose_name_plural': 'Hospital settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='hospital_singleton')],
            },
        ),
    ]
