# Generated by Django 5.2.17 on 2026-09-30 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentphone',
            name='number',
            field=models.CharField(help_text='Country code with no spaces, for example +919326543972.', max_length=40, validators=[django.core.validators.RegexValidator(message='Use an international number starting with + and country code, without spaces; for example +919405644319.', regex='^\\+[1-9][0-9]{7,14}$')]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(help_text='Country code with no spaces, for example +919405644319.', max_length=40, validators=[django.core.validators.RegexValidator(message='Use an international number starting with + and country code, without spaces; for example +919405644319.', regex='^\\+[1-9][0-9]{7,14}$')]),
        ),
    ]
