# Generated by Django 5.2.17 on 2026-09-30 21:07

import cms.storage
import cms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_appointmentphone_number_alter_hospital_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='certificate',
            field=models.FileField(blank=True, help_text='Private PDF, accessible only to authorized website administrators.', storage=cms.storage.PrivateCertificateStorage(), upload_to='certification/', validators=[cms.validators.pdf_upload]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='certificate_url',
            field=models.CharField(blank=True, editable=False, max_length=1000, validators=[cms.validators.safe_asset_url]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='certification_image',
            field=models.ImageField(blank=True, help_text='Private file, accessible only to authorized website administrators.', storage=cms.storage.PrivateCertificateStorage(), upload_to='certification/', validators=[cms.validators.image_upload]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='certification_image_url',
            field=models.CharField(blank=True, editable=False, max_length=1000, validators=[cms.validators.safe_asset_url]),
        ),
    ]
